version: "3.5"

services:
  postgres-id:
    image: postgres:15.4-alpine3.18
    container_name: postgres-id
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U habrpguser -d habrdb' ]
      interval: 10s
      timeout: 30s
      retries: 10
    volumes:
      - 'postgres_id_storage:/var/lib/postgresql/data'
    ports:
      - '127.0.0.1:5431:5432'
    env_file:
      - './postgres.env'
    networks:
      - postgres_network
  migrator:
    container_name: migrator
    restart: no
    build:
      context: .
      dockerfile: ./migrator/Dockerfile
    env_file:
      - './service.env'
    networks:
      - postgres_network
  marketplace-id:
    container_name: marketplace-id
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '0.0.0.0:7171:7171'
    env_file:
      - './service.env'
    networks:
      - postgres_network
      - marketplace_network
# Volumes.
volumes:
  postgres_id_storage:
    driver: local

# Networks.
networks:
  marketplace_network:
    name: marketplace_network
    external: true
  postgres_network:
    name: postgres_network