name: Deploy to Hosting
on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Deploy code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          script: |
            cd ./marketplace/${{ secrets.repository }} && git pull
            docker network create marketplace_network || true
            docker compose -p ${{ secrets.repository }} up -d --no-deps --build migrator
            docker compose -p ${{ secrets.repository }} up -d --no-deps --build ${{ secrets.repository }}
            docker image prune -f
